<?php

namespace AppBundle\Repository;

/**
 * MovieCrewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieCrewRepository extends \Doctrine\ORM\EntityRepository
{
}
