# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt # si ej change l'algorithùe d'encoding , cela change aussi la facon dont il est stocké en base

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chamonix_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html

            # Note: potentiellement , les routes ne sont pas toujours identiques
            form_login:
                login_path: login #route permettant l'affichage du formulaire
                check_path: login #route permettant de checker la validité du formulaire
                csrf_token_generator: security.csrf.token_manager
            
            logout:
                path:   /logout
                target: /
            
            provider: chamonix_provider

    access_control:
        # require ROLE_ADMIN for /admin* --> Ne pas oublier d'avoir le bon role dans Entity User 
        #- { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admin/[a-z]+/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/admin/[a-z]+/new, roles: ROLE_ADMIN }
        - { path: ^/admin/[a-z]+/delete/\d+, roles: ROLE_ADMIN } #gere le cas departement non généré par le crud
        - { path: ^/admin/[a-z]+, roles: ROLE_USER }
        - { path: ^/ , roles: IS_AUTHENTICATED_ANONYMOUSLY } #status present de base chez symfony

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER